### ISSUE TITLE
how to start this code

### ISSUE THREAD

**Issue by cheshicheng** [G00fY2/version-compare#1]
hello,i am from china,i want to know how to  quick start

**Comment by G00fY2** [comment]
What exactly is your question?
You find explanation [in the readme](https://github.com/G00fY2/version-compare#usage) and you can find the implementation [inside my sample app](https://github.com/G00fY2/version-compare/blob/1207775100fd4d076659d944a2802a0ae9f690c0/sample/src/main/kotlin/com/g00fy2/versioncomparesample/MainActivity.kt#L32).
