### ISSUE TITLE
[JUnit] Version has been compiled by a more recent version of the Java Runtime (class file version 55.0)

### ISSUE THREAD

**Issue by kelvinharron** [G00fY2/version-compare#10]
Hi g00fy, we've been using version-compare for quite some time now and the new bump highlighted an incompatibility with our unit tests

> java.lang.UnsupportedClassVersionError: com/g00fy2/versioncompare/Version has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

As I understand, you would have compiled with Java 11? Is there changes we need with our junit setup to ensure compatibility going forward? 

Our Junit 4 configuration is using Android API 28 Platform for the JRE.

I can migrate the tests to espresso as version-compare compiles and runs fine in app. Thanks.

**Comment by G00fY2** [comment]
Hey, you are right. Looks like last release was unintentionally compiled with Java 11. Should not affect actual usage, but I released a new version [1.3.7](https://github.com/G00fY2/version-compare/releases/tag/1.3.7) wich is compiled with Java 8 again. Let me know if everything is working again. :blush:

**Comment by kelvinharron** [comment]
Awesome, thank you for your prompt fix! Working great on our unit tests now ⭐
