### ISSUE TITLE
Publish somewhere besides jcenter

### ISSUE THREAD

**Issue by mattdsteele** [G00fY2/version-compare#11]
Recently JFrog announced they'll be sunsetting the jcenter registry: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

From a cursory look, it looks like Maven Central is their recommended alternative https://search.maven.org/

**Comment by G00fY2** [comment]
Thanks for reporting, I'm actually planing to move to MavenCentral soon (within the next weeks). Will keep you updated.

**Comment by G00fY2** [comment]
Version [1.4.0](https://github.com/G00fY2/version-compare/releases/tag/1.4.0) is now available on MavenCentral. Unfortunately I had to change the _groupId_ and by that the package name. Check out the [migration guide](https://github.com/G00fY2/version-compare/releases/tag/1.4.0) in the release notes.
