### ISSUE TITLE
Version("15.0.20220923") > Version("15.0.21") returns true instead of false

### ISSUE THREAD

**Issue by sdzshn3** [G00fY2/version-compare#13]
Version("15.0.20220923") > Version("15.0.21") returns true instead of false
can  you pls verify and fix it

**Comment by G00fY2** [comment]
Hi, this is the expected behavior. `20220923` is higher than `21`. I guess you expected `21` to be treated as `21000000`, but thats not how [SemVer dictates the comparison](https://semver.org/#spec-item-11):
> Major, minor, and patch versions are always compared numerically.
