### ISSUE TITLE
Maintain two major versions in parallel 

### ISSUE THREAD

**Issue by chlegou** [G00fY2/version-compare#4]
Hi again :) 

This isn't an issue, as much it's a new feature suggestion.

Now I'm planning to maintain two major branches in my app as this article is indicating : 
Link: https://github.com/GitTools/GitVersion/issues/1309
Link: https://gitversion.readthedocs.io/en/latest/git-branching-strategies/gitflow-examples/#support-branches

They could be 2.x  or 1.3.x or why not many others.

I want to control each branch minor version supported for end users.

For example, if the user is using 1.3.x, he must have at least v1.3.15.

But if using 2.x, he must have at least v2.1.3

As a suggestion, it could be : 

    new VersionCompare("1.3.47").with("1.3.x").isAtLeast("1.3.15"); // true
    new VersionCompare("1.3.47").with("2.x").isAtLeast("1.3.15"); // false

I hope this feature will be accepted. :-)

**Comment by G00fY2** [comment]
Hi,
sorry for replying so late. And of course you're welcome to suggest new features!

I think I understand your requirement, but to be honest I don't like to add too specific features to this library. I would suggest you to build a simple helper method by yourself and check the [major](https://g00fy2.github.io/version-compare/com/g00fy2/versioncompare/Version.html#getMajor--) and [patch](https://g00fy2.github.io/version-compare/com/g00fy2/versioncompare/Version.html#getPatch--) level in a switch case e.g. I think this would also be clearer to read and maintain.
