### ISSUE TITLE
Support for SNAPSHOT versions

### ISSUE THREAD

**Issue by Flo354** [G00fY2/version-compare#5]
Hi there,

Some projects have a versioning like "1.1-SNAPSHOT" for active development version very unstable. It is way before PRE-ALPHA.

Could you support it?

Thanks,

**Comment by G00fY2** [comment]
Hi Florian,
thanks for reaching out.

I think supporting SNAPSHOT is a nice addition. From my understanding Snapshots have no  build version (SNAPSHOT-1 or something)!? So I won't check for that part if a SNAPSHOT version is detected.

Maybe I find time to add this request this weekend.

**Comment by G00fY2** [comment]
Added with 1.3.3 (https://github.com/G00fY2/version-compare/commit/4f496896fc26b2dd6fe927f2a06b7886188db787).

**Comment by Flo354** [comment]
Thanks!
