### ISSUE TITLE
No hashCode() implementation

### ISSUE THREAD

**Issue by ivansopin** [G00fY2/version-compare#8]
The `Version` class is missing the `hashCode()` method while having the `equals()` method, resulting in dangerous behavior when used inside a collection such as set.

**Comment by G00fY2** [comment]
Thanks for reaching out.

Fixed with c1d685e

**Comment by ivansopin** [comment]
That was quick, thanks.

**Comment by ivansopin** [comment]
Are you planning to release this new version to Maven soon?

**Comment by G00fY2** [comment]
I already released the new version ([1.3.5](https://github.com/G00fY2/version-compare/releases/tag/1.3.5)). :wink:

**Comment by ivansopin** [comment]
Awesome, you rock!
